import {
  AllIcon,
  BestOfSugarPopIcon,
  BodyCareIcon,
  BodyLotionIcon,
  BodySprayIcon,
  ComboIcon,
  ConditionerIcon,
  CorporateGiftingIcon,
  EyeOutlineIcon,
  FaceIcon,
  FootCreamIcon,
  HairMaskIcon,
  HairOilIcon,
  HairSerumIcon,
  HandCreamIcon,
  HandWashIcon,
  LipIcon,
  LipstickSetGiftIcon,
  MakeupKitIcon,
  NailIcon,
  ShampooIcon,
  ShowerGelIcon,
  SkincareIcon,
  SoapIcon,
  SugarMerchIcon,
  SugarSetIcon,
  ValueSetIcon,
} from "../icons";

export const bath_and_body = {
  id: 1,
  level: 2,
  label: "Bath & Body",
  category: "bath_and_body",
  subCategories: [
    {
      id: 1,
      level: 3,
      label: "Shower Gels",
      category: "shower_gels",
      icon: ShowerGelIcon,
    },
    {
      id: 2,
      level: 3,
      label: "Soaps",
      category: "soaps",
      icon: SoapIcon,
    },
    {
      id: 3,
      level: 3,
      label: "Body Lotion",
      category: "body_lotion",
      icon: BodyLotionIcon,
    },
    {
      id: 4,
      level: 3,
      label: "Body Sprays",
      category: "body_sprays",
      icon: BodySprayIcon,
    },
    {
      id: 5,
      level: 3,
      label: "Hand Wash",
      category: "hand_wash",
      icon: HandWashIcon,
    },
    {
      id: 6,
      level: 3,
      label: "Foot Cream",
      category: "foot_cream",
      icon: FootCreamIcon,
    },
    {
      id: 7,
      level: 3,
      label: "Hand Cream",
      category: "hand_cream",
      icon: HandCreamIcon,
    },
  ],
};

export const sugar_pop = {
  id: 2,
  level: 2,
  label: "Sugar Pop",
  category: "sugar_pop",
  subCategories: [
    {
      id: 1,
      level: 3,
      label: "Lips",
      category: "lips",
      icon: LipIcon,
    },
    {
      id: 2,
      level: 3,
      label: "Eyes",
      category: "eyes",
      icon: EyeOutlineIcon,
    },
    {
      id: 3,
      level: 3,
      label: "Face",
      category: "face",
      icon: FaceIcon,
    },
    {
      id: 4,
      level: 3,
      label: "Nails",
      category: "nails",
      icon: NailIcon,
    },
    {
      id: 5,
      level: 3,
      label: "Skincare",
      category: "skincare",
      icon: SkincareIcon,
    },
    {
      id: 6,
      level: 3,
      label: "Body Care",
      category: "body_care",
      icon: BodyCareIcon,
    },
    {
      id: 7,
      level: 3,
      label: "Best of Sugar Pop",
      category: "best_of_sugar_pop",
      icon: BestOfSugarPopIcon,
    },
  ],
};

export const hair_care = {
  id: 3,
  level: 2,
  label: "Hair Care",
  category: "hair_care",
  subCategories: [
    {
      id: 1,
      level: 3,
      label: "Shampoo",
      category: "shampoo",
      icon: ShampooIcon,
    },
    {
      id: 2,
      level: 3,
      label: "Conditioner",
      category: "conditioner",
      icon: ConditionerIcon,
    },
    {
      id: 3,
      level: 3,
      label: "Hair Oil",
      category: "hair_oil",
      icon: HairOilIcon,
    },
    {
      id: 4,
      level: 3,
      label: "Serum",
      category: "serum",
      icon: HairSerumIcon,
    },
    {
      id: 5,
      level: 3,
      label: "Hair Mask",
      category: "hair_mask",
      icon: HairMaskIcon,
    },
    {
      id: 6,
      level: 3,
      label: "Combos",
      category: "combos",
      icon: ComboIcon,
    },
    {
      id: 7,
      level: 3,
      label: "View All",
      category: "view_all",
      icon: AllIcon,
    },
  ],
};

export const gifting = {
  id: 4,
  level: 2,
  label: "Gifting",
  category: "gifting",
  subCategories: [
    {
      id: 1,
      level: 3,
      label: "Lipstick Sets",
      category: "lipstick_sets",
      icon: LipstickSetGiftIcon,
    },
    {
      id: 2,
      level: 3,
      label: "Sugar Merch",
      category: "sugar_merch",
      icon: SugarMerchIcon,
    },
    {
      id: 3,
      level: 3,
      label: "Value Sets",
      category: "value_sets",
      icon: ValueSetIcon,
    },
    {
      id: 4,
      level: 3,
      label: "Makeup Kits",
      category: "makeup_kits",
      icon: MakeupKitIcon,
    },
    {
      id: 5,
      level: 3,
      label: "Corporate Gifting",
      category: "corporate_gifting",
      icon: CorporateGiftingIcon,
    },
    {
      id: 6,
      level: 3,
      label: "Sugar Sets",
      category: "sugar_sets",
      icon: SugarSetIcon,
    },
  ],
};
