import {
  TestIcon,
  ValueSetsIcon,
  MakeupKitIcon,
  GiftIcon,
} from "../../../../icons";

export const bath_and_body = {
  id: 1,
  level: 2,
  label: "Bath & Body",
  category: "bath_and_body",
  subCategories: [
    {
      id: 1,
      level: 3,
      label: "Shower Gels",
      category: "shower_gels",
      icon: TestIcon,
    },
    {
      id: 2,
      level: 3,
      label: "Soaps",
      category: "soaps",
      icon: TestIcon,
    },
    {
      id: 3,
      level: 3,
      label: "Body Lotion",
      category: "body_lotion",
      icon: TestIcon,
    },
    {
      id: 4,
      level: 3,
      label: "Body Sprays",
      category: "body_sprays",
      icon: TestIcon,
    },
    {
      id: 5,
      level: 3,
      label: "Hand Wash",
      category: "hand_wash",
      icon: TestIcon,
    },
    {
      id: 6,
      level: 3,
      label: "Foot Cream",
      category: "foot_cream",
      icon: TestIcon,
    },
    {
      id: 7,
      level: 3,
      label: "Hand Cream",
      category: "hand_cream",
      icon: TestIcon,
    },
  ],
};

export const sugar_pop = {
  id: 2,
  level: 2,
  label: "Sugar Pop",
  category: "sugar_pop",
  subCategories: [
    {
      id: 1,
      level: 3,
      label: "Lips",
      category: "lips",
      icon: TestIcon,
    },
    {
      id: 2,
      level: 3,
      label: "Eyes",
      category: "eyes",
      icon: TestIcon,
    },
    {
      id: 3,
      level: 3,
      label: "Face",
      category: "face",
      icon: TestIcon,
    },
    {
      id: 4,
      level: 3,
      label: "Nails",
      category: "nails",
      icon: TestIcon,
    },
    {
      id: 5,
      level: 3,
      label: "Skincare",
      category: "skincare",
      icon: TestIcon,
    },
    {
      id: 6,
      level: 3,
      label: "Body Care",
      category: "body_care",
      icon: TestIcon,
    },
    {
      id: 7,
      level: 3,
      label: "Best of Sugar Pop",
      category: "best_of_sugar_pop",
      icon: TestIcon,
    },
  ],
};

export const hair_care = {
  id: 3,
  level: 2,
  label: "Hair Care",
  category: "hair_care",
  subCategories: [
    {
      id: 1,
      level: 3,
      label: "Shampoo",
      category: "shampoo",
      icon: TestIcon,
    },
    {
      id: 2,
      level: 3,
      label: "Conditioner",
      category: "conditioner",
      icon: TestIcon,
    },
    {
      id: 3,
      level: 3,
      label: "Hair Oil",
      category: "hair_oil",
      icon: TestIcon,
    },
    {
      id: 4,
      level: 3,
      label: "Serum",
      category: "serum",
      icon: TestIcon,
    },
    {
      id: 5,
      level: 3,
      label: "Hair Mask",
      category: "hair_mask",
      icon: TestIcon,
    },
    {
      id: 6,
      level: 3,
      label: "Combos",
      category: "combos",
      icon: TestIcon,
    },
    {
      id: 7,
      level: 3,
      label: "View All",
      category: "view_all",
      icon: TestIcon,
    },
  ],
};

export const gifting = {
  id: 4,
  level: 2,
  label: "Gifting",
  category: "gifting",
  subCategories: [
    {
      id: 1,
      level: 3,
      label: "Lipstick Sets",
      category: "lipstick_sets",
      icon: TestIcon,
    },
    {
      id: 2,
      level: 3,
      label: "Sugar Merch",
      category: "sugar_merch",
      icon: TestIcon,
    },
    {
      id: 3,
      level: 3,
      label: "Value Sets",
      category: "value_sets",
      icon: ValueSetsIcon,
    },
    {
      id: 4,
      level: 3,
      label: "Makeup Kits",
      category: "makeup_kits",
      icon: MakeupKitIcon,
    },
    {
      id: 5,
      level: 3,
      label: "Corporate Gifting",
      category: "corporate_gifting",
      icon: GiftIcon,
    },
    {
      id: 6,
      level: 3,
      label: "Sugar Sets",
      category: "sugar_sets",
      icon: TestIcon,
    },
  ],
};
