import {
  BankIcon,
  BoxIcon,
  CalendarIcon,
  ChatIcon,
  ClapperIcon,
  GrowingSalesIcon,
  HandCoinIcon,
  HeadsetIcon,
  HomeIcon,
  ReviewIcon,
  SettingIcon,
  ShopIcon,
  SpeakerIcon,
  TeamIcon,
  TruckIcon,
  UsersIcon,
} from "./icons";

export const sidebarData = [
  {
    id: 1,
    label: "Dashboard",
    icon: HomeIcon,
    path: "/",
    disable: false,
  },
  {
    id: 2,
    label: "Users",
    icon: UsersIcon,
    path: "/users",
    disable: true,
  },
  {
    id: 3,
    label: "Team",
    icon: TeamIcon,
    path: "/team",
    disable: true,
  },
  {
    id: 4,
    label: "Vendors",
    icon: ShopIcon,
    path: "/vendors",
    disable: true,
  },
  {
    id: 5,
    label: "Products",
    icon: BoxIcon,
    path: "/products",
    disable: true,
  },
  {
    id: 6,
    label: "Orders",
    icon: TruckIcon,
    path: "/orders",
    disable: true,
  },
  {
    id: 7,
    label: "Transactions",
    icon: BankIcon,
    path: "/transactions",
    disable: true,
  },
  {
    id: 8,
    label: "Calendar",
    icon: CalendarIcon,
    path: "/calendar",
    disable: true,
  },
  {
    id: 9,
    label: "Blogs & Videos",
    icon: ClapperIcon,
    path: "/blogs_and_videos",
    disable: false,
  },
  {
    id: 10,
    label: "Marketing & Ads",
    icon: SpeakerIcon,
    path: "/marketing_and_ads",
    disable: true,
  },
  {
    id: 11,
    label: "Sales Reports",
    icon: GrowingSalesIcon,
    path: "/sales_reports",
    disable: true,
  },
  {
    id: 12,
    label: "Refunds & Returns",
    icon: HandCoinIcon,
    path: "/refunds_and_returns",
    disable: true,
  },
  {
    id: 13,
    label: "Reviews & Ratings",
    icon: ReviewIcon,
    path: "/reviews_and_ratings",
    disable: true,
  },
  {
    id: 14,
    label: "Customer Support",
    icon: HeadsetIcon,
    path: "/customer_support",
    disable: true,
  },
  {
    id: 15,
    label: "Chat & Messages",
    icon: ChatIcon,
    path: "/chat_and_messages",
    disable: true,
  },
  {
    id: 16,
    label: "Settings",
    icon: SettingIcon,
    path: "/settings",
    disable: true,
  },
];
