import { TestIcon } from "../../../../icons";
import {
  TransferLipstickIcon,
  MatteLipstickIcon,
  LiquidLipstickIcon,
  PowderLipstickIcon,
  CrayonLipstickIcon,
  SatinLipstickIcon,
  BulletLipstickIcon,
  LipGlossIcon,
  HiShineLipstickIcon,
  LipLinerIcon,
  LipGlitterIcon,
  LipTintAndSatinIcon,
  AllIcon,
  LipPrimerIcon,
  LipstickRemoverIcon,
  LipBalmIcon,
  TintedLipBalmIcon,
  LipstickSetIcon,
  LipstickComboIcon,
  LipPaletteIcon,
} from "../icons";

export const lipsticks = {
  id: 1,
  level: 2,
  label: "Lipsticks",
  category: "lipsticks",
  icon: TestIcon,
  subCategories: [
    {
      id: 1,
      level: 3,
      label: "Transfer Proof Lipstick",
      category: "transfer_proof_lipstick",
      icon: TransferLipstickIcon,
    },
    {
      id: 2,
      level: 3,
      label: "Matte Lipstick",
      category: "matte_lipstick",
      icon: MatteLipstickIcon,
    },
    {
      id: 3,
      level: 3,
      label: "Liquid Lipstick",
      category: "liquid_lipstick",
      icon: LiquidLipstickIcon,
    },
    {
      id: 4,
      level: 3,
      label: "Powder Lipstick",
      category: "powder_lipstick",
      icon: PowderLipstickIcon,
    },
    {
      id: 5,
      level: 3,
      label: "Crayon Lipstick",
      category: "crayon_lipstick",
      icon: CrayonLipstickIcon,
    },
    {
      id: 6,
      level: 3,
      label: "Satin Lipstick",
      category: "satin_lipstick",
      icon: SatinLipstickIcon,
    },
    {
      id: 7,
      level: 3,
      label: "Bullet Lipstick",
      category: "bullet_lipstick",
      icon: BulletLipstickIcon,
    },
    {
      id: 8,
      level: 3,
      label: "Lip Gloss",
      category: "lip_gloss",
      icon: LipGlossIcon,
    },
    {
      id: 9,
      level: 3,
      label: "Hi-Shine Lipstick",
      category: "hi_shine_lipstick",
      icon: HiShineLipstickIcon,
    },
    {
      id: 10,
      level: 3,
      label: "Lip Liner",
      category: "lip_liner",
      icon: LipLinerIcon,
    },
    {
      id: 11,
      level: 3,
      label: "Lip Glitter",
      category: "lip_glitter",
      icon: LipGlitterIcon,
    },
    {
      id: 12,
      level: 3,
      label: "Lip Tint & Stain",
      category: "lip_tint_and_stain",
      icon: LipTintAndSatinIcon,
    },
    {
      id: 13,
      level: 3,
      label: "View All",
      category: "view_all",
      icon: AllIcon,
    },
  ],
};
export const lip_care = {
  id: 2,
  level: 2,
  label: "Lip Care",
  category: "lip_care",
  icon: TestIcon,
  subCategories: [
    {
      id: 1,
      level: 3,
      label: "Lip Primer & Scrub",
      category: "lip_primer_and_scrub",
      icon: LipPrimerIcon,
      description: "Preps lips for smooth application.",
    },
    {
      id: 2,
      level: 3,
      label: "Lipstick Fixer & Remover",
      category: "lipstick_fixer_and_remover",
      icon: LipstickRemoverIcon,
      description: "Ensures long wear and easy removal.",
    },
    {
      id: 3,
      level: 3,
      label: "Lip Balm",
      category: "lip_balm",
      icon: LipBalmIcon,
      description: "Moisturizes and nourishes dry lips.",
    },
    {
      id: 4,
      level: 3,
      label: "Tinted Lip Balm",
      category: "tinted_lip_balm",
      icon: TintedLipBalmIcon,
      description: "Hydration with a hint of color.",
    },
  ],
};
export const lipstick_set_and_combo = {
  id: 3,
  level: 2,
  label: "Lipstick Set & Combo",
  category: "lipstick_set_and_combo",
  icon: TestIcon,
  subCategories: [
    {
      id: 1,
      level: 3,
      label: "Lipstick Set",
      category: "lipstick_set",
      icon: LipstickSetIcon,
      description: "Multiple shades in one set.",
    },
    {
      id: 2,
      level: 3,
      label: "Lipstick Combo",
      category: "lipstick_combo",
      icon: LipstickComboIcon,
      description: "Perfectly paired lip products.",
    },
    {
      id: 3,
      level: 3,
      label: "Lip Palette",
      category: "lip_palette",
      icon: LipPaletteIcon,
      description: "Versatile palette with various shades.",
    },
    {
      id: 4,
      level: 3,
      label: "View All",
      category: "view_all",
      icon: AllIcon,
      description: "Explore all sets and combos.",
    },
  ],
};
